
on: [push]
jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
    - run: |
        curl -u "${{secrets.PAT_TOKEN}}" \
         -H "Accept: application/vnd.github.everest-preview+json" \
         -H "Content-Type: application/json" \
         https://github.com/HarshDhingraDevops/testrepo/actions/workflows/main.yml/dispatches \
         --data '{"ref": "main"}'
