
on: [push]
jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
    - name: Test
      uses: actions/github-script@v6
      with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            const result = await github.rest.actions.createWorkflowDispatch({
              owner: 'HarshDhingraDevops',
              repo: 'testrepo',
              workflow_id: 'main.yml',
              ref: 'main'
            })
            console.log(result)
