
on: [push]
jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      run: |
        curl -X POST 'https://github.dev.us.corp/UKG/suiteserviceability-accelerate-demo/actions/workflows/suiteserviceability-accelerate-demo-main-workflow.yml/dispatches' \
        -H 'Accept: application/vnd.github.everest-preview+json' \
        -H 'Authorization: Bearer ${{ secrets.PAT_TOKEN }}' \ \
        -d '{"ref":"main"}'
