name: Clone Different Repo

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout different repo
        uses: actions/checkout@v2
        with:
          repository: HarshDhingraDevops/testrepo
          ref: main
      
      - name: Build and Test
        run: |
          git checkout main
          echo "Your data" > filename.txt
          git add .
          git commit -m "testing"
          git push
         
