
on: [push]
jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
    - name: Test
      run: |
          curl -X POST 'https://github.com/HarshDhingraDevops/testrepo/actions/workflows/main.yml/dispatches' \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -d '{"ref":"main"}'
