name: Clone Different Repo

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout different repo
        uses: actions/checkout@v2
        with:
          repository: HarshDhingraDevops/testrepo
          ref: main
      
      - name: Build and Test
        run: |
          # Add build and test commands here based on your project's requirements
          echo "Build and test commands go here"
