name: Clone Different Repo

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout different repo
        uses: actions/checkout@v3
        with:
          repository: HarshDhingraDevops/testrepo
      
      - name: Build and Test
        run: ls -ltr
